### PR TITLE
Initial translation for the French Language version.

### PR DESCRIPTION
**Pull request by malavv**
I am trying to get the manual set-up for a new locale.

### CODE REVIEW

**Comment by rocketman768** [comment]
:+1:

**Comment by malavv** [comment]
Hey Phillip,

It seems we need to add a Webhook from the Github repository for the Manual
to the ebook on Gitbook for it to trigger a rebuild. I do not have access
to the Github repository settings to put in place this webhook. Could you
look it up?

**Comment by rocketman768** [comment]
I assume I should not do this by linking to the github repo from within gitbook? If that's the case, do you know what goes here:

hooks

**Comment by malavv** [comment]
@rocketman768 pardon the image but I don't know how to explain this otherwise.

1 - Go to the book.
base

2- Settings sidebar
settings_sidebar

3- Select Github and enter the repo
brewtarget_manual

4 - Obtain the webhook. You can copy to clipboard and add it to Github.
webhook

**Comment by rocketman768** [comment]
Done!

**Pull request merged**
